id = "jjmagit"
name = "jjmagit"
version = "0.0.1"
schema_version = 1
authors = ["Jakob Hellermann <jakobhellermann@protonmail.com>"]
description = "todo"
repository = "todo"

[language_servers.jjmagit]
name = "jjmagit-language-server"
languages = ["jjmagit"]


[grammars.jjmagit]
repository = "https://github.com/jakobhellermann/jjmagit-treesitter"
rev = "4c1894420854ca2ce45fd9ff95bd4273cc2dda40"
